spring:
  application:
    name: vuee-spring
  data:
    mongodb:
      host: 119.23.243.88
      database: admin
      username: root
      password: password
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:static/,classpath:/static/,classpath:src/main/resources/static,file:src/main/resources/static
  redis:
    database: 1
    # Redis服务器地址
    host: 119.23.243.88
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456qwe
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8
server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
  address: 0.0.0.0
minio:
  endpoint: https://minio.220608.xyz/
  port: 443
  accessKey: 3e7KEg3qNKSW6yb1
  secretKey: 4LL6gc93d4S2YtLQHlyXTwDHqUdrqVAW
  bucketName: test
  validate-ssl: false